# Generated by Django 3.2.3 on 2021-05-31 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='is_trabajador',
            field=models.BooleanField(default=False),
        ),
    ]
