# Generated by Django 3.2.3 on 2021-05-31 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_usuarios_is_trabajador'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiculos',
            old_name='arrendatario_id',
            new_name='usuario_id',
        ),
    ]
