# Generated by Django 3.2.3 on 2021-05-31 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_arrendatario_id_vehiculos_usuario_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arriendos',
            name='fecha_termino',
            field=models.DateTimeField(blank=True),
        ),
    ]
