# Generated by Django 3.2.3 on 2021-05-31 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_arriendos_fecha_termino'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arriendos',
            name='fecha_termino',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
