# Generated by Django 3.2.3 on 2021-06-04 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_arriendos_fecha_termino'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arriendos',
            name='fecha_inicio',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='arriendos',
            name='precio',
            field=models.IntegerField(blank=True),
        ),
    ]
