# Generated by Django 3.2.3 on 2021-06-04 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210604_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arriendos',
            name='precio',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
